[package]
name = "rust-vdl"
version = "0.1.0"
edition = "2021"
authors = ["Peter Lunneberg"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"
directories = "5.0.0"
fermi = "0.3.0"
tokio = "1.27.0"
