refresh_rate: 30 seconds

appenders:
  runtime:
    kind: file
    path: "logs/runtime.log"
    encoder:
      pattern: "{d}: {l} {M} \\(line {L}\\) - {m}{n}"

root:
  level: info
  appenders:
    - runtime
