name: Build rust-vdl

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.styl"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Dioxus.toml"
      - "package-lock.json"
      - "package.json"
      - "rust-toolchain.toml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**.styl"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Dioxus.toml"
      - "package-lock.json"
      - "package.json"
      - "rust-toolchain.toml"
  
  workflow_dispatch:
    
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: false

defaults:
  run:
    working-directory: ./rust-vdl

jobs:
  build:
    strategy:
      matrix:
        config:
          - { name: "MacOS", os: macos-latest }
          - { name: "Linux", os: ubuntu-latest }
          - { name: "Windows", os: windows-latest }
    
    runs-on: ${{matrix.config.os}}
    
    steps:
    - uses: actions/checkout@v3
    
    # ---------- Set up the environment ----------
    - name: MacOS Setup
      if: startsWith(matrix.config.os, 'macos')
      run: |
        brew install node
        node --version
        npm --version
    
    - name: Linux Setup
      if: startsWith(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs
        node --version
        npm --version
    
    - name: Windows Setup
      if: startsWith(matrix.config.os, 'windows')
      run: |
        choco install nodejs
        node --version
        npm --version
    
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Setup Dioxus CLI
      run: |
        cargo install dioxus-cli
    
    # ---------- Build the project ----------
    - name: Build Project
      run: dioxus build --release
